### ISSUE TITLE
when I choose a repo it says that it's not a repo but it is

### ISSUE THREAD

**Issue by ghost** [baronleonardo/SideGit#1]
I choose a folder that I am very sure is a git repo but it brings an error saying: "This path doesn't have a GIT repo".

I checked the code to find a complex logic when all you need to do is check for a folder called .git. if it exists then it's a git repo, if not then it's not.

**Comment by baronleonardo** [comment]
you need to put the script files at the same place as the executable file ( SideGit )

**Comment by baronleonardo** [comment]
Solved by [446f6fc](https://github.com/baronleonardo/SideGit/commit/446f6fce6ff5000b03133aec733f1597ae55c70b)
