### ISSUE TITLE
SideGit icons have a problem

### ISSUE THREAD

**Issue by SaraElDeeb** [baronleonardo/SideGit#3]
![_20160627_235018](https://cloud.githubusercontent.com/assets/12938684/16397019/314d7322-3cc2-11e6-92cb-9675efc8d5e7.JPG)

should it appear like this? because this doesn't make any sense to me.. they don't represent their actions.

**Comment by baronleonardo** [comment]
[v1.0.1](https://github.com/baronleonardo/SideGit/releases/tag/v1.0.1) solve the problem
